on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install zsh
        run: sudo apt-get install -y zsh
      - run: make test
